### ISSUE TITLE
MemberViewの親機・子機一覧に自分を表す目印を表示する

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#103]
名前一覧の自分の欄の横に薄い文字で "You" とかNowPlayingみたいなインジケータがあったほうが良くないですか？

**Comment by bldsky** [comment]
どうだろう、あっても困らないとは思います。めちゃくちゃ欲しいとは思わないですね。と思ったけどデフォルトのアイコン使うならあったほうがいいかな？

**Comment by yaplus** [comment]
個人的には優先度はそこまで高くないかなとは思うんだけど、今のMemberViewだとDJが上にデカデカと断りなしに表示されてるので、初見だとこれが自分の端末だと勘違いするだろうなと思った  
今のMemeberViewは元々仮のつもりだったけど、残りの時間的に小改良（DJ・リスナーのラベルをつける等）に留まりそうだし、この辺の分かりづらさ（言葉の少なさ）はなんとかしておきたい

**Comment by bldsky** [comment]
確かに勘違いしそうなのでそこらへん直感的にする改良はいいですね。

**Comment by amylaseF85** [comment]
"You"みたいなのはあってもいいかもしれない

> 今のMemberViewだとDJが上にデカデカと断りなしに表示されてるので初見だとこれが自分の端末だと勘違いするだろうなと思った

これには確かにと思うところがある

NowPlayingは、MemberViewにそんなに多くの情報がいるか？と思う

**Comment by yaplus** [comment]
「NowPlayingみたいなインジケータ」を自分の横に表示するのであって「NowPlayingを表示する」わけじゃないです

**Comment by amylaseF85** [comment]
> 「NowPlayingみたいなインジケータ」を自分の横に表示するのであって「NowPlayingを表示する」わけじゃないです

あ、なるほど

**Comment by yaplus** [comment]
https://github.com/enpitut2019/dj-yusaku/issues/103#issuecomment-568951138 のようなことがあるので、MemberViewの自分は今親機が表示されてる場所に表示して、メンバー一覧に誰が親かを示すインジケータを表示するようにしたほうがわかりやすい可能性がある
