### ISSUE TITLE
ListenerConnectionViewのDJ一覧に現在のセッション参加人数を表示する

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#104]
DJ名の横に"(現在参加してる人数)/8" みたいな（チャットルーム的な）表示があったほうが良くないですか？

**Comment by bldsky** [comment]
良いですね。あとDJ選択画面にそのDJのセッションの現在の参加人数(n/8)の表記とかするのはどうでしょうか？

**Comment by amylaseF85** [comment]
> 良いですね。あとDJ選択画面にそのDJのセッションの現在の参加人数(n/8)の表記とかするのはどうでしょうか？

ListenerController = DJ選択画面じゃない？

**Comment by yaplus** [comment]
ListenerConnectionViewはDJ選択画面ですね

**Comment by amylaseF85** [comment]
これはなんとなく欲しいと思う

**Comment by bldsky** [comment]
やってます

**Comment by bldsky** [comment]
母数8と7表示するならどっちがいいですか？(DJ含むか含まないか)

**Comment by yaplus** [comment]
@bldsky 
母数は8かなあ

**Comment by yaplus** [comment]
#109 やった
