### ISSUE TITLE
PlayerQueueのpublicメンバに対するリファクタリング

### ISSUE THREAD

**Issue by amylaseF85** [enpitut2019/dj-yusaku#105]
関係ないけど PlayerQueue のメンバで外から参照しかされてないやつはpublic から private(set)にしたいな  
単なるリファクタリングだから暇ができたときにやりたい

_Originally posted by @yaplus in https://github.com/enpitut2019/dj-yusaku/pull/99#issuecomment-568950008_

**Comment by yaplus** [comment]
今のmaster見たらそもそもpublicメンバ1つもなかった（天才）  
ConnectionControllerと勘違いしてたかもしれんし、そっちの方も既にprivate(set)になってるはず
