### ISSUE TITLE
使用しているライブラリのライセンス表記

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#112]
- **[SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON/blob/master/LICENSE)** MITライセンス
- **[SnapKit](https://github.com/SnapKit/SnapKit/blob/develop/LICENSE)** MITライセンス
- **[Swifter](https://github.com/mattdonnelly/Swifter/blob/master/LICENSE)** MITライセンス

アプリ内に表示する方法とiOSの設定画面から開けるアプリ情報に表示する方法があるらしい

**Comment by tsuu32** [comment]
Japan NFC Readerってアプリが参考になるかも
比較してSettingsで気になったところ
* （User ProfileとかVersionのような）タップしてアクションが起こるわけでないセルをタップしても暗くなる
* ABOUT USで人をタップしてしたときSafariに飛ぶ（SFSafariViewControllerの方がいい気もする）

**Comment by yaplus** [comment]
#115 #116
やってる
