### ISSUE TITLE
SearchView表示したらキーボードがパッと出てくる

### ISSUE THREAD

**Issue by tsuu32** [enpitut2019/dj-yusaku#114]
現在の実装では、SearchViewを開いたら（タブの真ん中のタップしたら）次にsearchbarのtextfieldをタップするという動作が必要になる。

SearchViewを表示したら即searchbarがactiveになってキーボードも出てくるってのが良さそう。

（まだ検索してないときにSearchViewに履歴やおすすめが表示されるのであればこの機能は必要なさそうだけど、今からそれは実装しなそうなので）

**Comment by bldsky** [comment]
面倒くささを減らせるのでめちゃくちゃいいですね

**Comment by tsuu32** [comment]
自分でもやってみたんですがいい感じになりませんでした。
searchbar右隣にCancelが表示された状態（searchbarがactiveな状態）でモーダルが出てきてくれると嬉しんですが、そうする方法がわかりませんでした。

https://qiita.com/star__hoshi/items/ade50e5dcdbf7024a16f を参考にして試してみました（navigationItemではなくtableView.tableHeaderViewを使った）が、「モーダルが出てくる→searchbarがactiveになる→キーボードが出てくる」と同時に起こってほしいものが段階的に起こるためちょっとアレな感じがしました。

**Comment by bldsky** [comment]
自分は今 #117 の作業をしているため、Assignしていたのですが一旦取り消します。ごめんなさい。#117 が終わってまだ残っていたら再びAssignします。

**Comment by yaplus** [comment]
困難な理由もちゃんと書いてあるし、発表までに実装が無理そうならこのIssueは閉じちゃっていいと思う  
一応検索キーワードのヒントを表示してるしそこは手動でも許せないかなって思ったり

**Comment by yaplus** [comment]
無理でした
