### ISSUE TITLE
Apple Musicを契約してない人がNew Sessionできる

### ISSUE THREAD

**Issue by tsuu32** [enpitut2019/dj-yusaku#122]
現在Apple Musicを契約してない端末ではNew Sessionをできるし、New Requestで検索もできるし、曲タップすればRequested Songsに追加される。ストップボタンもスキップボタンも動く。ただし曲は流れることはない。

どうするか。

1. このままにする
2. New Sessionを押せなくする or 押したらアラートが出る
3. DJの状態でNew Requestを押せなくする or 押したらアラートが出る

他もあるかも

**Comment by amylaseF85** [comment]
2が良いと思う
できるならボタンの文章を
「need AppleMusic signing 」とかにする

**Comment by tsuu32** [comment]
New Session押せなくすると、俺みたいにApple Music契約してない人はほぼなにもできなくて悲しい。
でも、今のままだと日本語読めない人に曲流れねーじゃねえかってクレームつけられそうって話があった。

Apple Music契約してない人がDJになったとき、
New Session押せるけど、アラートが出る。
曲検索もできるけど、曲をタップするとアラートが出て追加もされない。
という、二段階アラート方式を考えたけどどうだろう。

**Comment by tsuu32** [comment]
#135 で解決
