### ISSUE TITLE
clearSongsメソッドしてもコントロールセンターには停止した曲がある問題

### ISSUE THREAD

**Issue by tsuu32** [enpitut2019/dj-yusaku#132]
```swift
self.mpAppController.nowPlayingItem = nil
```
すればいいんじゃないかと思うんだけど誰か試してみてください。

**Comment by amylaseF85** [comment]
> ```swift
> self.mpAppController.nowPlayingItem = nil
> ```

これをPlayerQueueのclearSongs()に追加して、
clearSongs()が呼ばれているstartDJ()、startListener()を呼ぶような操作
（再接続して「新規セッション」または「セッションに参加」を押す）を行っても
コントロールセンターはクリアにならなかったです

強いて変わったところは、この記述を入れたら再生してた曲が先頭に戻った

**Comment by amylaseF85** [comment]
標準のミュージックアプリでも、アプリを落とさない限り残り続けてる

**Comment by amylaseF85** [comment]
いろいろ調べてたんだけど、他の音楽再生できるアプリ（AppStoreにあった単純に音楽を再生できるアプリやAmazonMusicのアプリ）は終了するとコントロールセンターのミュージックのところが何もない状態（またはアプリが起動する前の状態）に戻ってた
いちいち特別な処理書いてるとも思えないから、アプリが死ぬときに呼ばれるものがあると思うけど...

AVAudioPlayerならうまくいくとか、こっちからコントロールセンターを制御するとかなのかな

**Comment by yaplus** [comment]
AVAudioPlayerの方でMPNowPlayingInfoCenter

```swift
try? AVAudioSession.sharedInstance().setActive(false, options: .notifyOthersOnDeactivation)
MPNowPlayingInfoCenter.default().nowPlayingInfo = [:]

```

すると行けそうな感じはするんだけど、同じようなこと（なんとかして`MPNowPlayingInfoCenter.default().nowPlayingInfo`に`nil`や`[:]`を代入する）を`clearSongs()`の中で試してもダメだった

https://stackoverflow.com/questions/55873529/unable-to-set-nowplayinginfo-to-nil
https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter

**Comment by yaplus** [comment]
ちなみにAVAudioPlayerだとApple Musicの曲が再生できない

**Comment by tsuu32** [comment]
https://stackoverflow.com/questions/54173972/rearrange-mediaplayer-music-queue-ios
MPMusicPlayerControllerのキュー管理はありえん困難って書いてある。

私は他に方法思いつかないし、このままでもまあ良さそうということで、これに対して特に何もしないということにします。
