### ISSUE TITLE
RequestQueueのリファクタリング（Queueの操作を抽象化）

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#17]
### 概要

- RequestQueueはMusicDataModel使わずにMedia Playerのqueueを使うようにする
  - 現在のRequestQueueと同じように機能するが、シングルトンでMedia Player（とそのqueue）を保持するクラスを作成する。つまり、RequestQueueの名前を変えて、MusicDataModelの配列を削除して、代わりにMedia Playerのインスタンスを持つようにする。
- SearchViewControllerでは MusicDataModelを引き続き使う（名前もSearchResultとかに変えると良い）

**Comment by amylaseF85** [comment]
- ArtworkURLだけ単独でRequestQueueに持たせる？
