### ISSUE TITLE
リスナーの時にDJになるボタンを押したら接続を一度切るようにする

### ISSUE THREAD

**Issue by bldsky** [enpitut2019/dj-yusaku#21]
そうしないとリスナーになった後にDJボタンを押すとリスナー兼DJみたいなのができるため

**Comment by tsuu32** [comment]
[join as the DJ]ボタンを押すと`ConnectionController.shared.initialize(isParent: true, displayName: UIDevice.current.name)`が呼ばれるので、接続は切れるような実装となっています。

**Comment by bldsky** [comment]
はい
