### ISSUE TITLE
楽曲追加時に「処理中...」のようなダイアログをつける

### ISSUE THREAD

**Issue by amylaseF85** [enpitut2019/dj-yusaku#29]
#28 のFixに伴い、楽曲を追加するとき他の操作で再生キューが操作されている場合は待ち時間が発生するようになったため、「処理中...」等フィードバックを追加する

**Comment by yaplus** [comment]
実はどこかのタイミングで待ち時間を半分(4秒→2秒)にして体感的に問題ない程度にしたので閉じる
