### ISSUE TITLE
SearchMusicTableViewCcellのボタンデザイン変更

### ISSUE THREAD

**Issue by bldsky** [enpitut2019/dj-yusaku#30]
現在は+のデザインになっていますが、わかりにくいし押しにくいためデザインを変えたいです。(セル全体をボタンにしたりなど)アイデア募集中です。

**Comment by yaplus** [comment]
実は今までの+ボタンは見た目に対して判定が左にずれていたので、それを直すために af19c82d6097c5a02e55105a047dcbbb745294c4 で今のボタンに修正しました。  
ちなみに純正のミュージックアプリではライブラリの楽曲のプレイリストへの追加モーダルで System.plus.circle（ e52a65f17cdd4c3adbe7f769d6bc2a680ada770b 以前のボタンと同じ形）が、Apple Musicの曲をライブラリに追加する画面でSystem.plus（現在のボタンと同じ形）が使われているので、どっちの形がいいかというのは決め難い部分があります。  
セル全体をボタンにするのであれば、追加するボタンであることを明確にしたいので、単純に判定だけ大きくして見た目は現在のままにする程度がいいと考えています。

**Comment by yaplus** [comment]
#51 で解決
