### ISSUE TITLE
New Sessionの動作を変更

### ISSUE THREAD

**Issue by tsuu32** [enpitut2019/dj-yusaku#34]
[join as a Listener] ボタンの下に書かれているラベルの文字列。

現状 [join as a Listener] ボタンを押しても他のリスナとは接続しないが、そういう仕様にしたかったのか？

**Comment by yaplus** [comment]
"New Session" / "Join the Session" にしようかと思ってる

**Comment by tsuu32** [comment]
現在DJからDJになるときDJは他のピアとの接続を切断するが、曲はそのままの状態となっている（クリアされない）
"New Session"とするなら曲をクリアするべき...？

**Comment by tsuu32** [comment]
"connects with other DJ or listener friends"自体は 031aef8 で消えてました

**Comment by bldsky** [comment]
#126 でやってました。
