### ISSUE TITLE
履歴、オススメ、ランキングなどデンモクにある機能の追加

### ISSUE THREAD

**Issue by bldsky** [enpitut2019/dj-yusaku#36]
意見くれ

**Comment by amylaseF85** [comment]
履歴はいいけど、オススメ・ランキングは必要ないと思います
レビューの時に聞いてみてもいいけど、これはデンモクではないので

**Comment by yaplus** [comment]
履歴は #57 で実装(グレーアウト)  
オススメとか上にあるように必要ないのでcloseします
