### ISSUE TITLE
参加する際にニックネームを登録するようにする

### ISSUE THREAD

**Issue by bldsky** [enpitut2019/dj-yusaku#37]
誰がリクエストした曲かわかるようにする、DJが意図しないリスナーを削除できるようにするため参加する際ニックネームをつけたほうがいいと僕は思うのですがどうでしょうか？

**Comment by bldsky** [comment]
何も入力せず入るとデフォルトのニックネームが登録されると面白いかもしれません

**Comment by bldsky** [comment]
### アイデア
* twitterのユーザー検索を実装して選択させる

**Comment by yaplus** [comment]
#70 で解決
