### ISSUE TITLE
コンフリクトすると面倒なファイルをなんとかする

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#4]
## 概要

- ファイル構成をいじると. pbxprojがコンフリクトするが、JSONっぽい形式だからといって手動でマージすると容易に壊れる
- 同様に、InterfaceBuilderで編集するファイル(.storyboard) も、オブジェクト間の参照情報を持っていたりするので、XML形式のように見えて壊れる
- めちゃくちゃになる前になんとかしておきたい

## 対策（案）

- [mergepbx](https://github.com/simonwagner/mergepbx) をみんなで導入する： `brew install mergepbx`  
その他の方法としては、
    - ~.gitattributeに `*.pbxproj binary merge=union` を追加する（最も手軽だが便宜的）~ コンフリクト解決できなさそう
    - [XcodeGen](https://techlife.cookpad.com/entry/2019/04/26/110000) をみんなで導入する（面倒くさそう） 
- .storyboardの編集（ViewやModelの設計）のは一人で担当する
    - 検索画面のように具体的な実装部分だけ穴埋めするようにファイルを作っていく
    - これも.gitattributeで `*.storyboard binary` した方がいいかも 

参考：https://thoughtbot.com/blog/xcode-and-git-bridging-the-gap

## やってほしいこと

皆さんの意見をください。

**Comment by tsuu32** [comment]
mergepbxを導入するので、
 .git/config に
```
#driver for merging Xcode project files
[merge "mergepbx"]
        name = Xcode project files merger
        driver = mergepbx %O %A %B
```
を追記する。
