### ISSUE TITLE
子機のNowPlaying表示

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#43]

**Comment by yaplus** [comment]
な〜にが😴じゃい

@bldsky 
![4d7a7b2f7580fe1df52f0f380db28582](https://user-images.githubusercontent.com/3463901/69346604-6a95ba00-0cb6-11ea-8be6-e65b1bd39171.png)

**Comment by amylaseF85** [comment]
#46 で解決
> - 子機のnowPlaying表示
    - そのためのMessageData型を追加、親から子にはMessageData型をJSONにしたものをsend
