### ISSUE TITLE
バッテリーセーバーモードにした時のアラートが読みづらい

### ISSUE THREAD

**Issue by amylaseF85** [enpitut2019/dj-yusaku#45]
バッテリーセーバーから復帰する方法を示したアラートが読みづらい

ただし、
> アラートのOK押した時に呼ばれるcompletionHandlerに画面を暗くするコードを入れとくと直るんだけど、そうするとアラートが出てる最中にアプリがバックグラウンドになったときにおかしな挙動になった

**Comment by yaplus** [comment]
あとバッテリーセーバーが「明るさの自動調整」がオンになってるときに挙動が怪しい

**Comment by yaplus** [comment]
#111 でやりました
