### ISSUE TITLE
再生キューの先頭に対して削除操作を行ったときに挙動がおかしくなる

### ISSUE THREAD

**Issue by amylaseF85** [enpitut2019/dj-yusaku#52]
曲をいくつかリクエストする
↓
現在再生している曲（＝一番上にある曲）に対して削除操作をする
↓
セルは残り続けるのでもう1回削除操作をする
↓
再生され続けたままアプリが落ちる
（例：子機からリクエストを投げると親機が落ちる）

**Comment by bldsky** [comment]
現在再生している曲を消すと全体的に不具合が出るから、現在再生している曲は編集不可にするか編集前に次の曲に変えてから編集完了させるかにしたいですね

**Comment by amylaseF85** [comment]
@amylaseF85 が先頭を編集不可能にする修正を（今週のレビュー向け）
@bldsky が先頭の編集がちゃんとできるように（その先のレビュー向け）
します

**Comment by yaplus** [comment]
バグの原因を特定できたらここに書いていただけると助かります

**Comment by yaplus** [comment]
削除機能を廃止して、代替(不便を緩和しうる)機能を実装済み #57 #58 #68
