### ISSUE TITLE
ローカル・Apple Music版という括りをやめて、画面ごとのProjectにする

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#6]
## 概要

Apple Musicの検索機能が思ったより簡単にできそうなので、ローカルのライブラリ検索に時間を割くのは無駄かもしれないので、今やっている作業を踏まえて画面の製作とその機能実装ごとのProjectに修正したいと考えています。  

#### Projectの分け方の例（括弧内は今作業している人）

- 各画面の製作 (@yaplus)
- リクエスト実装 (なし)
    - 再生キューにある曲の再生など
    - 主なフレームワーク: [MediaPlayer](https://developer.apple.com/documentation/mediaplayer)
- 検索実装(@bldsky , @yaplus)
    - AppleMusicからの曲名検索と再生キューへの追加
    - 主なフレームワークやライブラリ: [MusicKit](https://developer.apple.com/musickit/), [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON)
- Bluetooth接続実装(@tsuu32)
    - 親機・子機のペアリングと管理
    - 主なフレームワークやライブラリ: [MultipeerConnectivity](https://developer.apple.com/documentation/multipeerconnectivity), [MultiPeer](https://github.com/dingwilson/MultiPeer)

## やってほしいこと

是非をお願いします。

**Comment by amylaseF85** [comment]
俺がリクエスト実装やればOKですか？

**Comment by yaplus** [comment]
@amylaseF85 
やりたければ是非やってほしい。多分MediaQuery云々の話だとは思うんだけど、Apple Musicの曲の再生については https://dev.classmethod.jp/smartphone/iphone/ios-11-apple-music-api-search/#play あたりが参考になると思う。  
曲の再生に必要な情報があれば適宜MusicDataModelに追加していただきたい。

**Comment by yaplus** [comment]
僕は検索画面終わったらペアリング画面作成に移るつもりでいます。

**Comment by amylaseF85** [comment]
と、いうことはリクエスト機能に@bldskyは来れる？

**Comment by yaplus** [comment]
@amylaseF85 
@bldsky の都合はわからんけど、画面作るのはながら作業でもできるので、僕が一緒にリクエスト画面の処理考えても大丈夫です。

**Comment by amylaseF85** [comment]
当初の予定だとプログラムをいじくる人間を限定してしまう（ペアプロのような状態を作る）という話だったと思うんですけど、その前提は維持されますか？
別に仕事量がBluetooth関連>>リクエスト機能というのであれば、リソースを割いてもらってもいいです

**Comment by amylaseF85** [comment]
検索機能の実装はもうすぐ終わるから、あとリクエスト機能とBlueToothの2手に分かれてその先を進めることができるということ？

**Comment by amylaseF85** [comment]
別に開発の形式的なところに拘っているとかではなく、知識的に不安要素があるので質問しました

**Comment by yaplus** [comment]
@amylaseF85 
ペアプロっぽくしたいのはそれはそうだから、Bluetooth関連とリクエストの2手に分かれた方がいいかもしれないね

**Comment by amylaseF85** [comment]
そしたら、何卒そのようにお願いします
