### ISSUE TITLE
チュートリアル画面の検討

### ISSUE THREAD

**Issue by amylaseF85** [enpitut2019/dj-yusaku#64]
チュートリアル画面について、以前議論した時には「Viewに吹き出しが出るように」ということだったが、
吹き出しで実現するのはかなり手間がかかりそうである。
（参考：https://qiita.com/ddd503/items/2bd35b86313f1761e8e0）

なので、一部だけをハイライトして説明の文言を表示する方法
（参考：https://iganin.hatenablog.com/entry/2019/08/29/204223）
を使って実装しようと考えているが、問題ないか。

吹き出しで簡単な方法、あるいはもっと良いデザインがあればお願いしたい。

**Comment by yaplus** [comment]
スポットライトみたいにハイライトして文字被せればいいと思う  
ハイライトする方がanimateでハイライトの位置変えられる？だろうし

**Comment by yaplus** [comment]
形は変わったけど #77 でできてるから閉じます
