### ISSUE TITLE
iOS 12以降のモーダルでPageControl表示するとおかしくなる

### ISSUE THREAD

**Issue by tsuu32** [enpitut2019/dj-yusaku#82]
TutorialViewController.swiftの問題

_Originally posted by @yaplus in https://github.com/enpitut2019/dj-yusaku/pull/81#issuecomment-568267595_

**Comment by yaplus** [comment]
フルスクリーンモーダルで出して背景色つければ大丈夫そうな感じがする  
iOS 12以降の半モーダルはPageControlとの相性が悪そう

**Comment by amylaseF85** [comment]
やりまーす
他に回るべきだったらまたなんか言ってくださーい

**Comment by yaplus** [comment]
@amylaseF85 
これは僕がやるのでやらないでください（UIのやつと一緒にやる）

**Comment by yaplus** [comment]
@amylaseF85 
https://github.com/enpitut2019/dj-yusaku/issues/112 やってほしい

**Comment by yaplus** [comment]
https://github.com/enpitut2019/dj-yusaku/pull/96/commits/a4994d7d1ea261acf54e6598282c3e8bc850f1ce で解決
