### ISSUE TITLE
ListenerConnectionViewControllerのDJ一覧で自分自身が増殖する

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#83]
😭

![IMG_5827](https://user-images.githubusercontent.com/3463901/71323121-0fecb980-2513-11ea-9cfa-e567b824995e.PNG)

**Comment by tsuu32** [comment]
バグが発生する具体的な手順を書いて欲しい

**Comment by yaplus** [comment]
1. DJになる
2. アプリを終了する（タスクごと終了する）
3. アプリを再度開いてJoin as a listenerする
4. 前回のDJ情報が残ってる（？）

みたいな感じな気がする

**Comment by yaplus** [comment]
スリープから復帰したときにもスリープ前のconnectableDJsが増殖してる

1. Join as a listenerする
2. スリープする
3. スリープから復帰する
4. 復帰前にあったDJ一覧が追加され直されている（複製されている）

**Comment by tsuu32** [comment]
二つ目のは再現して確認した（simulatorがDJになってる状態で実機でJoin as a listenerして確認）

ひとつ目はひとつの端末だけで自分を見つけてしまってるということ？それとも二台？

**Comment by yaplus** [comment]
> ひとつ目はひとつの端末だけで自分を見つけてしまってるということ？それとも二台？

ひとつの端末だけで自分を見つけてしまってる

**Comment by tsuu32** [comment]
ひとつ目のは再現できない
アプリ終了したにも関わらずadvertiseが終了せず残ってるってことだと思うけど...

**Comment by yaplus** [comment]
なんか今自分でやっても再現できなかった

**Comment by yaplus** [comment]
ConnectionControllerのadvertiseやbrowseの開始・停止タイミングが制御し切れてない感じがするし一回ちゃんと洗い出したほうがいい気がする

**Comment by tsuu32** [comment]
いうほど制御し切れてないか？

**Comment by yaplus** [comment]
制御できてたらこういうバグは出ないと思う（このバグ結構前からあったし…）

**Comment by tsuu32** [comment]
ConnectionControllerのadvertiseやbrowseの開始・停止タイミングは問題ないと思うけどな

> このバグ結構前からあったし…

報告してほしい

**Comment by yaplus** [comment]
> 報告してほしい

すいません  
前に口頭で言った気がしてたけどIssue建てるべきだったね

#85 試してたら5つあったYapPhoneが3つに減ったりして謎

**Comment by tsuu32** [comment]
重複消えたから、そのYapPhone全部別のsessionからのadvertiseのはず
アプリがバックグラウンドになったときadvertiseをstopするとかを加えれば直ると思うけど...
Appleはバックグラウンドになったらadvertiseは止まると言っているんだけど

**Comment by yaplus** [comment]
あと、しばらく放置して今アプリを起動したら全部のYapPhoneが消えた  
タスクキルしてadvertiseが残ってる感があったのが謎だけどなんかのデーモンが走りっぱなしだったりするんだろうか

**Comment by yaplus** [comment]
今やったら https://github.com/enpitut2019/dj-yusaku/issues/83#issuecomment-568269116 でバグ再現した

**Comment by tsuu32** [comment]
@bldsky @amylaseF85 このバグが再現するか試して欲しいです
ちなみに私の環境では再現しません
手順:
アプリ起動してDJになる
アプリを終了する（上にフリックしてタスクキルするやつのこと）
アプリを起動してjoin as a listener押してDJ一覧画面を見る
そこに自分がいる→バグを再現できた
そこに自分はいない→バグは発生してない

**Comment by amylaseF85** [comment]
再現してます
iPhone XR or iPad mini (5th gen)

**Comment by yaplus** [comment]
@tsuu32 
iPhone 7だと再現しないそうです（ @bldsky 談）

**Comment by yaplus** [comment]
ハードウェアの問題っぽい  
A12チップ以降のiPhoneだとMultiPeerで飛ばす電波の種類が多かったりするのかな  
明示的にadvertiseやめるコード加えたほうが良さそう

**Comment by yaplus** [comment]
#113 で直った
