### ISSUE TITLE
DJがDJをやめてリスナーになったらPlayerQueueを初期化して再生している曲を止める

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#89]
タイトル通りです。  
今のままだと元DJが音楽を再生し続けてしまうし、別の接続しているDJから新しいリクエスト楽曲一覧が送られてくるまでTableViewがreloadされずに古い内容が残ってしまってる。  
再生キューのクリアは難しいかもしれないからせめて曲を止めるくらいはしてほしい。

### 再現手順

1. 端末AでDJになる
2. 端末Aでいくつか曲を追加する（リスナーからでも可）、曲の再生が始まる
3. 端末AがDJをやめて端末Bに接続する
  - この時点で端末Aから曲は流れ続けている
  - TableViewの表示もDJ時代の曲が残っている（リロードすれば消える？未確認）
4. 端末Bにリクエストを送ると曲一覧は更新されるが曲は流れ続ける
  - 端末AとBで同じApple Musicのアカウントだと曲の再生自体は止まるが、それは契約プランの制限によるため、端末AとBで別のアカウントだと曲は止まらないと思われる

**Comment by yaplus** [comment]
#99 でやってる

**Comment by amylaseF85** [comment]
#99 で解決
