### ISSUE TITLE
設定画面の変更がすぐ表示として反映されない

### ISSUE THREAD

**Issue by yaplus** [enpitut2019/dj-yusaku#90]
ONにしてからsessionボタン押すと、タイミングによって中身が変わってない時があった
（逆にOFFにしたときは起こらない）
仕様な気がするけど

_Originally posted by @amylaseF85 in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjIyNzE4MzQ0OnYy/pull_request_review_threads/discussion_

**Comment by yaplus** [comment]
直感的には、UserDefaultsが更新されたタイミングでNotificationか何か受け取って、SettingsVIewのルートViewにsetNeedsLayoutしてやれば良さそう

**Comment by tsuu32** [comment]
@yaplus 
> ONにしてからsessionボタン押すと、タイミングによって中身が変わってない時があった
（逆にOFFにしたときは起こらない）

このIssueってSettingsでNameを編集して戻ってきたときにそれが表示に反映されてないってバグについてかと思ったけど、そうじゃない？
（「Nameが空のとき、Nameをタップして名前を入れて（もちろんdone押して）Settingsに戻ってきたときそれが表示されてないというバグがある）

**Comment by yaplus** [comment]
@tsuu32 
それと同じだと思う  
WebViewでTwitterアカウント切り替えてから設定画面に戻ってきた時も反映されてない場合がある  
おそらく設定画面のView全体に更新をかけてやれば良さそうだけど…

**Comment by yaplus** [comment]
直った #101
