### ISSUE TITLE
親機名の不整合

### ISSUE THREAD

**Issue by amylaseF85** [enpitut2019/dj-yusaku#91]
## 再現条件

1. 親機・子機がアプリを起動し接続
2. 子機がReconnectを経由して親機と再接続
3. 子機が一度Requestに移ってからSessionを表示させる

この時、子機における親機名が端末名になっている場合がある
今のところ親機が1度もバックグラウンドになっていない場合にのみ発生を確認

**Comment by amylaseF85** [comment]
#86 とは別件（かもしれない）

**Comment by tsuu32** [comment]
> この時、子機における親機名が端末名になっている場合がある

親機の設定で、Twitterプロフィールを使わない設定かつNameが空の場合、親機名が端末名になっているのは想定された挙動です。

再現条件において、親機がTwitterにログインしているのか、Twitterのプロフィールを使う設定か、Nameは空かどうか教えてください

**Comment by tsuu32** [comment]
これはupdateMembersの`DispatchQueue`あたりが怪しい

**Comment by amylaseF85** [comment]
一応報告しとくと、再現条件において、
Twitterログイン：○
Twitterのプロフィールを使う：○（スイッチがオン）
Name：×（空の状態）
でした

**Comment by yaplus** [comment]
#93 で解決したはず
